version: '3'

services:
  mongo:
    container_name: mongo_server 
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

       
  mongo-express:
    container_name: mongo_client
    image: mongo-express
    ports:
     - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
 
  sarfo:
    container_name: sarfo_simulator
    image: sarfo-simulator
    build:
      context: .
    ports:
    - "8080:8080"